openapi: 3.0.3
info:
  title: Shopify Admin API (Subset for Products)
  version: 1.0.0
  description: |
    Minimal subset of the Shopify Admin REST API used by this agent.
    Base version: 2024-01. Auth via X-Shopify-Access-Token (private app token).
servers:
  - url: https://{shop}.myshopify.com/admin/api/2024-01
    description: Shopify store admin API
    variables:
      shop:
        default: rafa-ecommerce
        description: Shopify store prefix (without .myshopify.com)
components:
  securitySchemes:
    shopifyAccessToken:
      type: apiKey
      in: header
      name: X-Shopify-Access-Token
  schemas:
    ProductVariant:
      type: object
      properties:
        id:
          type: integer
          format: int64
          example: 1234567890
        price:
          type: string
          example: "19.99"
        compare_at_price:
          type: string
          example: "29.99"
          description: "Original price before discount. Set to enable sale pricing. Use null or same as price to disable sale."
    Product:
      type: object
      properties:
        id:
          type: integer
          format: int64
          example: 1234567890
        title:
          type: string
          example: Camiseta básica
        body_html:
          type: string
          example: "Descripcion del producto"
        variants:
          type: array
          items:
            $ref: '#/components/schemas/ProductVariant'
    ProductsResponse:
      type: object
      properties:
        products:
          type: array
          items:
            $ref: '#/components/schemas/Product'
    ProductResponse:
      type: object
      properties:
        product:
          $ref: '#/components/schemas/Product'
    CustomCollection:
      type: object
      properties:
        id:
          type: integer
          format: int64
          example: 987654321
        title:
          type: string
          example: Home Page
    CustomCollectionsResponse:
      type: object
      properties:
        custom_collections:
          type: array
          items:
            $ref: '#/components/schemas/CustomCollection'
    CustomCollectionResponse:
      type: object
      properties:
        custom_collection:
          $ref: '#/components/schemas/CustomCollection'
    Collect:
      type: object
      properties:
        id:
          type: integer
          format: int64
          example: 111222333
        product_id:
          type: integer
          format: int64
          example: 1234567890
        collection_id:
          type: integer
          format: int64
          example: 987654321
    CollectResponse:
      type: object
      properties:
        collect:
          $ref: '#/components/schemas/Collect'
paths:
  /products:
    get:
      operationId: listProducts
      summary: List products
      security:
        - shopifyAccessToken: []
      parameters:
        - name: limit
          in: query
          schema:
            type: integer
            minimum: 1
            maximum: 250
          description: Max products to return (Shopify default 50, max 250)
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProductsResponse'
        '401':
          description: Unauthorized (invalid Shopify token)
        '403':
          description: Forbidden
  /products/{product-id}:
    parameters:
      - name: product-id
        in: path
        required: true
        schema:
          type: integer
          format: int64
        description: Shopify product ID
    get:
      operationId: getProductById
      summary: Get product by ID
      security:
        - shopifyAccessToken: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProductResponse'
        '401':
          description: Unauthorized
        '404':
          description: Not found
  /custom-collections:
    get:
      operationId: listCustomCollections
      summary: List custom collections
      security:
        - shopifyAccessToken: []
      parameters:
        - name: limit
          in: query
          schema:
            type: integer
            minimum: 1
            maximum: 250
          description: Max collections to return (Shopify max 250)
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CustomCollectionsResponse'
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
    post:
      operationId: createCustomCollection
      summary: Create custom collection
      security:
        - shopifyAccessToken: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                custom_collection:
                  type: object
                  properties:
                    title:
                      type: string
      responses:
        '201':
          description: Created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CustomCollectionResponse'
        '400':
          description: Bad request
        '401':
          description: Unauthorized
  /collects:
    get:
      operationId: listCollects
      summary: List collects
      security:
        - shopifyAccessToken: []
      parameters:
        - name: product_id
          in: query
          schema:
            type: integer
            format: int64
        - name: collection_id
          in: query
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  collects:
                    type: array
                    items:
                      $ref: '#/components/schemas/Collect'
        '401':
          description: Unauthorized
    post:
      operationId: createCollect
      summary: Add product to collection
      security:
        - shopifyAccessToken: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                collect:
                  type: object
                  properties:
                    product_id:
                      type: integer
                      format: int64
                    collection_id:
                      type: integer
                      format: int64
      responses:
        '201':
          description: Created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CollectResponse'
        '400':
          description: Bad request
        '401':
          description: Unauthorized
  /collects/{collect-id}:
    delete:
      operationId: deleteCollect
      summary: Remove product from collection
      security:
        - shopifyAccessToken: []
      parameters:
        - name: collect-id
          in: path
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: Deleted
        '401':
          description: Unauthorized
    put:
      operationId: updateProduct
      summary: Update product (title/description/variants)
      security:
        - shopifyAccessToken: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                product:
                  type: object
                  properties:
                    id:
                      type: integer
                      format: int64
                    title:
                      type: string
                    body_html:
                      type: string
                    variants:
                      type: array
                      items:
                        $ref: '#/components/schemas/ProductVariant'
      responses:
        '200':
          description: Updated
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProductResponse'
        '400':
          description: Bad request
        '401':
          description: Unauthorized
        '404':
          description: Not found
security:
  - shopifyAccessToken: []
