# Rutas locales de arranque para dependencias WSO2 usadas por start_demo.sh

WSO2_ROOT=/Users/rafagranados/Develop/wso2
WSO2_IS_START_SCRIPT=/Users/rafagranados/Develop/wso2/wso2is-7.2.0/bin/wso2server.sh
WSO2_APIM_START_SCRIPT=/Users/rafagranados/Develop/wso2/wso2am-4.6.0/bin/api-manager.sh